version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  client:
    image: node:16.14.1
    command: sh -c "npm i --save && npm start"
    ports:
      - 3000:3000
    working_dir: /client
    environment:
      - ./client/.env
    volumes:
      - ./client:/client
    depends_on:
      - app

volumes:
  mongodb_data: